#!/usr/bin/env bash
# install nginx on web-01

sudo apt-get update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'

echo "Hello World!" | sudo tee /var/www/html/index.nginx-debian.html
sudo service nginx restart
#checking configuration
sudo nginx -t 
sudo killall -s HUP nginx
