#!/usr/bin/env bash

# Update package list and install nginx
sudo apt-get update
sudo apt-get install -y nginx

# Create a simple HTML file with "Hello World!"
echo "Hello World!" | sudo tee /var/www/html/index.html

# Configure nginx for 301 redirection
redirect_config="server {
    listen 80;
    server_name _;
    location /redirect_me {
    return 301 https://github.com/besthor;
}
}"

echo "$redirect_config" | sudo tee /etc/nginx/sites-available/redirect_me > /dev/null
sudo ln -s /etc/nginx/sites-available/redirect_me /etc/nginx/sites-enabled/
# Restart nginx to apply the changes
sudo service nginx restart
echo "Nginx configured for redirection successfully."
